rewards:
  - type: docking
    weight: 3
    params:
      protein_file: ./Mpro_7L11.pdb
      box: [-33, -15, -41, -9, 9, -17]
      protocols: ["vina-gpu"]
      timeout: 45
  - type: drug_likeliness
    weight: 1

run:
  random_seed: 42
